#include <postgres.h>
#include <fmgr.h>

PG_FUNCTION_INFO_V1(tsql_@TYPE_NAME1@_eq_@TYPE_NAME2@);
PG_FUNCTION_INFO_V1(tsql_@TYPE_NAME1@_ne_@TYPE_NAME2@);
PG_FUNCTION_INFO_V1(tsql_@TYPE_NAME1@_lt_@TYPE_NAME2@);
PG_FUNCTION_INFO_V1(tsql_@TYPE_NAME1@_le_@TYPE_NAME2@);
PG_FUNCTION_INFO_V1(tsql_@TYPE_NAME1@_gt_@TYPE_NAME2@);
PG_FUNCTION_INFO_V1(tsql_@TYPE_NAME1@_ge_@TYPE_NAME2@);
PG_FUNCTION_INFO_V1(tsql_@TYPE_NAME1@_cmp_@TYPE_NAME2@);

PG_FUNCTION_INFO_V1(tsql_@TYPE_NAME1@_pl_@TYPE_NAME2@);
PG_FUNCTION_INFO_V1(tsql_@TYPE_NAME1@_mi_@TYPE_NAME2@);
PG_FUNCTION_INFO_V1(tsql_@TYPE_NAME1@_mul_@TYPE_NAME2@);
PG_FUNCTION_INFO_V1(tsql_@TYPE_NAME1@_div_@TYPE_NAME2@);

static inline int32_t
@TYPE_NAME1@_cmp_@TYPE_NAME2@(TYPE_@TYPE_NAME1@ l, TYPE_@TYPE_NAME2@ r) {
  if (l == r) {
    return 0;
  } else if (l < r) {
    return -1;
  } else {
    return 1;
  }
}

Datum
tsql_@TYPE_NAME1@_eq_@TYPE_NAME2@(PG_FUNCTION_ARGS) {
  TYPE_@TYPE_NAME1@ l = GETARG_@TYPE_NAME1@(0);
  TYPE_@TYPE_NAME2@ r = GETARG_@TYPE_NAME2@(1);

  if (@TYPE_NAME1@_cmp_@TYPE_NAME2@(l, r) == 0)
    PG_RETURN_BOOL(1);
  else
    PG_RETURN_BOOL(0);
}

Datum
tsql_@TYPE_NAME1@_ne_@TYPE_NAME2@(PG_FUNCTION_ARGS) {
  TYPE_@TYPE_NAME1@ l = GETARG_@TYPE_NAME1@(0);
  TYPE_@TYPE_NAME2@ r = GETARG_@TYPE_NAME2@(1);

  if (@TYPE_NAME1@_cmp_@TYPE_NAME2@(l, r) != 0)
    PG_RETURN_BOOL(1);
  else
    PG_RETURN_BOOL(0);
}

Datum
tsql_@TYPE_NAME1@_lt_@TYPE_NAME2@(PG_FUNCTION_ARGS) {
  TYPE_@TYPE_NAME1@ l = GETARG_@TYPE_NAME1@(0);
  TYPE_@TYPE_NAME2@ r = GETARG_@TYPE_NAME2@(1);

  if (@TYPE_NAME1@_cmp_@TYPE_NAME2@(l, r) < 0)
    PG_RETURN_BOOL(1);
  else
    PG_RETURN_BOOL(0);
}

Datum
tsql_@TYPE_NAME1@_le_@TYPE_NAME2@(PG_FUNCTION_ARGS) {
  TYPE_@TYPE_NAME1@ l = GETARG_@TYPE_NAME1@(0);
  TYPE_@TYPE_NAME2@ r = GETARG_@TYPE_NAME2@(1);

  if (@TYPE_NAME1@_cmp_@TYPE_NAME2@(l, r) <= 0)
    PG_RETURN_BOOL(1);
  else
    PG_RETURN_BOOL(0);
}

Datum
tsql_@TYPE_NAME1@_gt_@TYPE_NAME2@(PG_FUNCTION_ARGS) {
  TYPE_@TYPE_NAME1@ l = GETARG_@TYPE_NAME1@(0);
  TYPE_@TYPE_NAME2@ r = GETARG_@TYPE_NAME2@(1);

  if (@TYPE_NAME1@_cmp_@TYPE_NAME2@(l, r) > 0)
    PG_RETURN_BOOL(1);
  else
    PG_RETURN_BOOL(0);
}

Datum
tsql_@TYPE_NAME1@_ge_@TYPE_NAME2@(PG_FUNCTION_ARGS) {
  TYPE_@TYPE_NAME1@ l = GETARG_@TYPE_NAME1@(0);
  TYPE_@TYPE_NAME2@ r = GETARG_@TYPE_NAME2@(1);

  if (@TYPE_NAME1@_cmp_@TYPE_NAME2@(l, r) >= 0)
    PG_RETURN_BOOL(1);
  else
    PG_RETURN_BOOL(0);
}

Datum
tsql_@TYPE_NAME1@_cmp_@TYPE_NAME2@(PG_FUNCTION_ARGS) {
  TYPE_@TYPE_NAME1@ l = GETARG_@TYPE_NAME1@(0);
  TYPE_@TYPE_NAME2@ r = GETARG_@TYPE_NAME2@(1);

  PG_RETURN_INT32(@TYPE_NAME1@_cmp_@TYPE_NAME2@(l, r));
}

Datum
tsql_@TYPE_NAME1@_pl_@TYPE_NAME2@(PG_FUNCTION_ARGS) {
  TYPE_@TYPE_NAME1@ l = GETARG_@TYPE_NAME1@(0);
  TYPE_@TYPE_NAME2@ r = GETARG_@TYPE_NAME2@(1);

  RETURN_@TYPE_NAME2@(l + r);
}

Datum
tsql_@TYPE_NAME1@_mi_@TYPE_NAME2@(PG_FUNCTION_ARGS) {
  TYPE_@TYPE_NAME1@ l = GETARG_@TYPE_NAME1@(0);
  TYPE_@TYPE_NAME2@ r = GETARG_@TYPE_NAME2@(1);

  RETURN_@TYPE_NAME2@(l - r);
}

Datum
tsql_@TYPE_NAME1@_mul_@TYPE_NAME2@(PG_FUNCTION_ARGS) {
  TYPE_@TYPE_NAME1@ l = GETARG_@TYPE_NAME1@(0);
  TYPE_@TYPE_NAME2@ r = GETARG_@TYPE_NAME2@(1);

  RETURN_@TYPE_NAME2@(l * r);
}

Datum
tsql_@TYPE_NAME1@_div_@TYPE_NAME2@(PG_FUNCTION_ARGS) {
  TYPE_@TYPE_NAME1@ l = GETARG_@TYPE_NAME1@(0);
  TYPE_@TYPE_NAME2@ r = GETARG_@TYPE_NAME2@(1);

  RETURN_@TYPE_NAME2@(l / r);
}
