CREATE FUNCTION tsql_@TYPE_NAME1@_um(tsql_@TYPE_NAME2@) RETURNS tsql_@TYPE_NAME3@ AS '/home/james/tdspsql/tdspsql.so' LANGUAGE C IMMUTABLE STRICT;
CREATE OPERATOR - ( PROCEDURE = tsql_@TYPE_NAME1@_um, RIGHTARG = tsql_@TYPE_NAME2@);

CREATE FUNCTION tsql_@TYPE_NAME1@_cmp_@TYPE_NAME2@(tsql_@TYPE_NAME1@, tsql_@TYPE_NAME2@) RETURNS INT4 AS '/home/james/tdspsql/tdspsql.so' LANGUAGE C IMMUTABLE STRICT;
CREATE OPERATOR CLASS tsql_@TYPE_NAME1@_@TYPE_NAME2@_ops DEFAULT FOR TYPE tsql_@TYPE_NAME2@ USING btree FAMILY tsql_int_ops AS
 OPERATOR 1 <,
 OPERATOR 2 <=,
 OPERATOR 3 =,
 OPERATOR 4 >=,
 OPERATOR 5 >,
 FUNCTION 1 tsql_@TYPE_NAME1@_cmp_@TYPE_NAME2@(tsql_@TYPE_NAME1@, tsql_@TYPE_NAME2@);

CREATE FUNCTION tsql_@TYPE_NAME1@_min(tsql_@TYPE_NAME1@, tsql_@TYPE_NAME1@) RETURNS tsql_@TYPE_NAME1@ AS '/home/james/tdspsql/tdspsql.so' LANGUAGE C IMMUTABLE STRICT;
CREATE AGGREGATE min(tsql_@TYPE_NAME1@) (SFUNC = tsql_@TYPE_NAME1@_min, STYPE = tsql_@TYPE_NAME1@);
CREATE FUNCTION tsql_@TYPE_NAME1@_max(tsql_@TYPE_NAME1@, tsql_@TYPE_NAME1@) RETURNS tsql_@TYPE_NAME1@ AS '/home/james/tdspsql/tdspsql.so' LANGUAGE C IMMUTABLE STRICT;
CREATE AGGREGATE max(tsql_@TYPE_NAME1@) (SFUNC = tsql_@TYPE_NAME1@_max, STYPE = tsql_@TYPE_NAME1@);

CREATE AGGREGATE sum(tsql_@TYPE_NAME1@) (SFUNC = tsql_@TYPE_NAME1@_pl_@TYPE_NAME1@, STYPE = tsql_@TYPE_NAME1@);

CREATE FUNCTION tsql_coalesce(tsql_@TYPE_NAME1@, tsql_@TYPE_NAME1@) RETURNS tsql_@TYPE_NAME1@ AS '/home/james/tdspsql/tdspsql.so', 'tsql_@TYPE_NAME1@_coalesce' LANGUAGE C IMMUTABLE;

