CREATE FUNCTION tsql_cast_@TYPE_NAME1@_@TYPE_NAME2@(tsql_@TYPE_NAME1@) RETURNS tsql_@TYPE_NAME2@ AS '/home/james/tdspsql/tdspsql.so' LANGUAGE C IMMUTABLE STRICT;
CREATE CAST (tsql_@TYPE_NAME1@ AS tsql_@TYPE_NAME2@) WITH FUNCTION tsql_cast_@TYPE_NAME1@_@TYPE_NAME2@(tsql_@TYPE_NAME1@) AS @CAST_TYPE@;
